import Head from "next/head";
import { Inter, Numans } from "@next/font/google";
import Button1 from "@/components/Button1";
import LineChart from "@/components/LineChart";
import Cards from "@/components/Cards";
import Sliders from "@/components/Sliders";
import { createContext, Dispatch, SetStateAction, useContext, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

type SelectYearContextType = {
  state: number;
  setState: Dispatch<SetStateAction<number>>;
};

export const SelectYearContext = createContext<SelectYearContextType>({} as SelectYearContextType);

export default function Home() {
  const [SelectYear, setSelectYear] = useState<number>(100);

  return (
    <SelectYearContext.Provider value={{ state: SelectYear, setState: setSelectYear }}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <Button1 /> */}
      <LineChart />
      {/* <Cards /> */}
      <Sliders />
    </SelectYearContext.Provider>
  );
}
